using ClinicVets.Models;
using ClinicVets.Repositories.interfacesrepo;
using Microsoft.Data.Sqlite;

namespace ClinicVets.Repositories;

<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> main

// alaa 
// this class between the ui and the data access layer 
// interface because we can have multiple implementations   
// implimintation of the ICustomerRepository interface using SQLite as the data store


<<<<<<< HEAD
=======
>>>>>>> 13bfe672cf043b4c83b8f39f62fc93493951aca9
=======
>>>>>>> main
public class CustomerRepository(string connectionString) : ICustomerRepository
{
    // return true if we have a customer with the same identity number in the table 
    public bool ExistsByIdentityNumber(string identityNumber)
    {
        using SqliteConnection connection = OpenConnection();
        using SqliteCommand command = connection.CreateCommand();
        command.CommandText =
            """
            SELECT COUNT(*)
            FROM Customers
            WHERE IdentityNumber = $identityNumber;
            """;
        command.Parameters.AddWithValue("$identityNumber", identityNumber);

        long count = (long)command.ExecuteScalar()!;
        return count > 0;
    }
// return the customer if we have a customer with the same identity number or phone number in the table
    public Customer? FindByIdentityOrPhone(string searchText)
    {
        using SqliteConnection connection = OpenConnection();
        using SqliteCommand command = connection.CreateCommand();
        command.CommandText =
            """
            SELECT Id, FullName, IdentityNumber, Phone, Email
            FROM Customers
            WHERE IdentityNumber = $searchText OR Phone = $searchText
            LIMIT 1;
            """;
        command.Parameters.AddWithValue("$searchText", searchText);

        using SqliteDataReader reader = command.ExecuteReader();
        return reader.Read() ? ReadCustomer(reader) : null;
    }


// return the customer if we have a customer with the same id in the table
    public Customer? FindById(int customerId)
    {
        using SqliteConnection connection = OpenConnection();
        using SqliteCommand command = connection.CreateCommand();
        command.CommandText =
            """
            SELECT Id, FullName, IdentityNumber, Phone, Email
            FROM Customers
            WHERE Id = $id;
            """;
        command.Parameters.AddWithValue("$id", customerId);

        using SqliteDataReader reader = command.ExecuteReader();
        return reader.Read() ? ReadCustomer(reader) : null;
    }

// create the role table with the details that we need to save about the role
    public Customer Add(Customer customer)
    {
        using SqliteConnection connection = OpenConnection();
        using SqliteCommand command = connection.CreateCommand();
        command.CommandText =
            """
            INSERT INTO Customers (FullName, IdentityNumber, Phone, Email)
            VALUES ($fullName, $identityNumber, $phone, $email);

            SELECT last_insert_rowid();
            """;
        command.Parameters.AddWithValue("$fullName", customer.FullName);
        command.Parameters.AddWithValue("$identityNumber", customer.IdentityNumber);
        command.Parameters.AddWithValue("$phone", customer.Phone);
        command.Parameters.AddWithValue("$email", customer.Email);

        long customerId = (long)command.ExecuteScalar()!;

        return new Customer
        {
            Id = (int)customerId,
            FullName = customer.FullName,
            IdentityNumber = customer.IdentityNumber,
            Phone = customer.Phone,
            Email = customer.Email
        };
    }

// private function to add a new customer to the table and return the customer with the id that generated by the database
    private SqliteConnection OpenConnection()
    {
        SqliteConnection connection = new(connectionString);
        connection.Open();

        using SqliteCommand command = connection.CreateCommand();
        command.CommandText = "PRAGMA foreign_keys = ON;";
        command.ExecuteNonQuery();

        return connection;
    }
    // private function to read the customer from the database and return the customer object 
    // with the details that we have in the data base

    private static Customer ReadCustomer(SqliteDataReader reader)
    {
        return new Customer
        {
            Id = reader.GetInt32(0),
            FullName = reader.GetString(1),
            IdentityNumber = reader.GetString(2),
            Phone = reader.GetString(3),
            Email = reader.GetString(4)
        };
    }
}
