using ClinicVets.Models;
using ClinicVets.Repositories.interfacesrepo;
using Microsoft.Data.Sqlite;

namespace ClinicVets.Repositories;
// alaa 
// implimintation of the IEmployeeRepository interface using SQLite as the data store
// the real implimintation of the repo so it well be connect with the data and return answer to the ui layer
public class EmployeeRepository(string connectionString) : IEmployeeRepository
{

    // return the employee if we have a employee with the same username in the table
    public Employee? FindByUsername(string username)
    {
        using SqliteConnection connection = OpenConnection();
        using SqliteCommand command = connection.CreateCommand();
        command.CommandText =
            """
            SELECT Employees.Id, Username, PasswordHash, EmployeeNumber, Email, IdentityNumber, Roles.Name AS RoleName
            FROM Employees
            INNER JOIN Roles ON Roles.Id = Employees.RoleId
            WHERE Username = $username;
            """;
        command.Parameters.AddWithValue("$username", username);

        using SqliteDataReader reader = command.ExecuteReader();
        if (!reader.Read())
        {
            return null;
        }

        return ReadEmployee(reader);
    }

    // return true if we have an employee with the same username, employee number, email, or identity number in the table
    public bool ExistsByRegistrationFields(string username, string employeeNumber, string email, string identityNumber)
    {
        using SqliteConnection connection = OpenConnection();
        using SqliteCommand command = connection.CreateCommand();
        command.CommandText =
            """
            SELECT COUNT(*)
            FROM Employees
            WHERE Username = $username
               OR EmployeeNumber = $employeeNumber
               OR Email = $email
               OR IdentityNumber = $identityNumber;
            """;
        command.Parameters.AddWithValue("$username", username);
        command.Parameters.AddWithValue("$employeeNumber", employeeNumber);
        command.Parameters.AddWithValue("$email", email);
        command.Parameters.AddWithValue("$identityNumber", identityNumber);

        long count = (long)command.ExecuteScalar()!;
        return count > 0;
    }

// add a new employee to the table and return the employee with the id that generated by the database
    public Employee Add(Employee employee)
    {
        using SqliteConnection connection = OpenConnection();
        int roleId = GetRoleId(connection, employee.Role);

        using SqliteCommand command = connection.CreateCommand();
        command.CommandText =
            """
            INSERT INTO Employees (Username, PasswordHash, EmployeeNumber, Email, IdentityNumber, RoleId)
            VALUES ($username, $passwordHash, $employeeNumber, $email, $identityNumber, $roleId);

            SELECT last_insert_rowid();
            """;
        command.Parameters.AddWithValue("$username", employee.Username);
        command.Parameters.AddWithValue("$passwordHash", employee.PasswordHash);
        command.Parameters.AddWithValue("$employeeNumber", employee.EmployeeNumber);
        command.Parameters.AddWithValue("$email", employee.Email);
        command.Parameters.AddWithValue("$identityNumber", employee.IdentityNumber);
        command.Parameters.AddWithValue("$roleId", roleId);

        long employeeId = (long)command.ExecuteScalar()!;

        return new Employee
        {
            Id = (int)employeeId,
            Username = employee.Username,
            PasswordHash = employee.PasswordHash,
            EmployeeNumber = employee.EmployeeNumber,
            Email = employee.Email,
            IdentityNumber = employee.IdentityNumber,
            Role = employee.Role
        };
    }

    private SqliteConnection OpenConnection()
    {
        SqliteConnection connection = new(connectionString);
        connection.Open();

        using SqliteCommand command = connection.CreateCommand();
        command.CommandText = "PRAGMA foreign_keys = ON;";
        command.ExecuteNonQuery();

        return connection;
    }

    private static int GetRoleId(SqliteConnection connection, StaffRole role)
    {
        using SqliteCommand command = connection.CreateCommand();
        command.CommandText = "SELECT Id FROM Roles WHERE Name = $name;";
        command.Parameters.AddWithValue("$name", role.ToString());

        object? value = command.ExecuteScalar();
        if (value is null)
        {
            throw new InvalidOperationException($"Role '{role}' does not exist in the database.");
        }

        return Convert.ToInt32(value);
    }

    private static Employee ReadEmployee(SqliteDataReader reader)
    {
        return new Employee
        {
            Id = reader.GetInt32(0),
            Username = reader.GetString(1),
            PasswordHash = reader.GetString(2),
            EmployeeNumber = reader.GetString(3),
            Email = reader.GetString(4),
            IdentityNumber = reader.GetString(5),
            Role = Enum.Parse<StaffRole>(reader.GetString(6))
        };
    }
}
